services:
  - type: web
    name: lawyerconnect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lawyerconnect-db
          property: connectionString

databases:
  - name: lawyerconnect-db
    databaseName: lawyerconnect
    user: lawyerconnect

